### ISSUE TITLE
Open High Low Close labels missing

### ISSUE THREAD

**Issue by merndev** [Kaktana/kaktana-react-lightweight-charts#1]
I am new to coding...
is it possible to show open high low close labels in chart with respect to crosshair ?

**Comment by AurelReb** [comment]
Hi,
The wrapper includes a special feature to achieve this. You can use the `legend` parameter on the `candleStickSeries`.

```javascript
let candleStickSeries = [{
  options: {...},
  data: [...],
  legend: "BTC/USD 30m"
}]
```

![Deepin Capture-écran_zone de sélection _20200421010357](https://user-images.githubusercontent.com/46166884/79807734-17f72180-836c-11ea-8fe0-c573dcb98826.png)

**Comment by merndev** [comment]
Thank You So Much... It worked...
