### ISSUE TITLE
Update to use latest version

### ISSUE THREAD

**Issue by nemani** [Kaktana/kaktana-react-lightweight-charts#10]
The version used in this repo (2.0.0) is pretty old. 
Are there any plans to update to the latest version (3.1.5) ?

Thanks for this project, helped a lot ! :smile:

**Comment by AurelReb** [comment]
Hi, currently I'm a bit busy to update to the latest version of lightweight charts.
However, any PR is appreciated ;) (btw thank you for #11)
I will probably work on the update on December/January

**Comment by burnside** [comment]
I accidentally found out today that an update would fix issue #6.

Combined candlestick + histogram charts don't work in 2.0.0 but seem to have been fixed somewhere along the line and are working in 3.2.0.

**Comment by lecampos** [comment]
Hi! 

Is there some tutorial that I can follow, so I can update it to 3.4.0 which is the current one? 

I will be very happy to share it after

**Comment by jtdaugh** [comment]
Sent up https://github.com/Kaktana/kaktana-react-lightweight-charts/pull/16 to update version
