### ISSUE TITLE
How to use UTC UNIX timestamp or ISO time format, to input candlestick data?

### ISSUE THREAD

**Issue by anuraagbarde** [Kaktana/kaktana-react-lightweight-charts#15]
Works
`{ time: '2018-10-25', open: 177.52, high: 180.50, low: 176.83, close: 179.07 },`

Does not work,
`{ time: '2018-10-21T19:20', open: 180.34, high: 180.99, low: 178.57, close: 179.85 },`

Also does not work,
`{ time: '1612729136', open: 180.34, high: 180.99, low: 178.57, close: 179.85 }`

Thanks.

**Comment by ParanoidAndroid19** [comment]
Hey, this works for me:
{time: 1614189239.965, open: 4.1196, high: 4.128, low: 4.119, close: 4.1226}

**Comment by anuraagbarde** [comment]
It expects as an number and not a string.

Thanks!
