### ISSUE TITLE
i con't change line color bottomColor,TopColor ... it shows only default color (areaSeries)

### ISSUE THREAD

**Issue by kamalshekar** [Kaktana/kaktana-react-lightweight-charts#3]
let options={
  
	topColor:'#4682b4',
    bottomColor: '#4682b4',
    lineColor: 'rgba(21, 146, 230, 1)',
    lineStyle: 0,
    lineWidth: 3,
    crosshairMarkerVisible: false,
    crosshairMarkerRadius: 3,
	layout: {
		backgroundColor: "#FFF",
	
	  },

	  grid: {
		vertLines: {
		  visible: false,
	 
		},
		horzLines: {
		  visible: false,
	 
		}
	  },
	  priceScale: {
		borderVisible: false,
		position: 'left',
		color:'red',
	  
	  },
	  timeScale: {
		borderVisible: false,
		borderColor: "red",
		

	  },
	  crosshair: {
		mode: CrosshairMode.Normal
	  },
	}
return(
 <Chart options={options}
 darkTheme={true}   addAreaSeries={add} autoWidth autoHeight />
)

**Comment by AurelReb** [comment]
Did you try to place these options on the areaSeries options?

```js
areaSeries = {
  data: ...,
  options: <the area options go here>
}
```

**Comment by AurelReb** [comment]
I close this issue as it seems not to be one
