### ISSUE TITLE
timeScale tickMarkFormatter property not working

### ISSUE THREAD

**Issue by nicholas-newman1** [Kaktana/kaktana-react-lightweight-charts#8]
**Code**
```
import Chart from 'kaktana-react-lightweight-charts';

const stockChart = () => {
  return (
    <Chart options={{
      timeScale: {
        borderColor: '#fff',
        tickMarkFormatter: time => 'TEST'
      }
    }} />
  )
};

export default stockChart;
```

**Expected Result**
Each tick mark on the time scale should say 'TEST'. Border color should be white.

**Actual Result**
No change in what each tick mark displays. Border color does change to white.

**Comment by nemani** [comment]
Not sure if this will help but check the [docs of tradingview/lightweight-charts at v2.0.0](https://github.com/tradingview/lightweight-charts/tree/v2.0.0/docs) which is what this repo uses. :)

**Comment by AurelReb** [comment]
@nicholas-newman1 Could you send me a [Codesandbox](https://codesandbox.io/) link so I can easily review your issue?
Thanks :)

**Comment by nicholas-newman1** [comment]
@AurelReb It looks like the tickMarkFormatter method was added in v3.0 of lightweight charts, which explains why adding in the property does nothing. Thanks anyways!

**Comment by KmaCoder** [comment]
As I can see in dependencies, now version 3.3 is used, but anyway tickMarkFormatter doesn't work
